### ISSUE TITLE
WeasyPrint not working with Python 2.x, leads to many other issues.

### ISSUE THREAD

**Issue by harperaa** [djaodjin/djaoapp#103]
(installTop) Allens-Mac:djaoapp allenharper$ pip install -r requirements.txt
...
...
Collecting WeasyPrint>=0.42 (from djaodjin-extended-templates==0.2.4->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/89/05/4eb7b5135bf94465a61b6ddfa6e84526cdc1b15385a3bed7aa86b5bda621/WeasyPrint-44.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0k/8xmmczvs2blc5dcf1dxdv0y00000gn/T/pip-install-4N6mmG/WeasyPrint/setup.py", line 20, in <module>
        'WeasyPrint does not support Python 2.x anymore. '
    RuntimeError: WeasyPrint does not support Python 2.x anymore. Please use Python 3 or install an older version of WeasyPrint.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0k/8xmmczvs2blc5dcf1dxdv0y00000gn/T/pip-install-4N6mmG/WeasyPrint/

This had me switch to Python3, which had a series of other issues to work through...related to python2 still being called in scripts...

(installTop) Allens-Mac:djaoapp allenharper$ make build-assets
cd . && /Users/allenharper/git/djaoapp/installTop/bin/python manage.py compilemessages
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
make: *** [djaoapp/locale/fr/LC_MESSAGES/django.mo] Error 1

switched to pip3 and things improved...but still issues....

(installTop) Allens-Mac:djaoapp allenharper$ make build-assets
cd . && /Users/allenharper/git/djaoapp/installTop/bin/python3 manage.py compilemessages
Use Jinja2 templates engine.
CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.
make: *** [djaoapp/locale/fr/LC_MESSAGES/django.mo] Error 1

worked through that one...then other issues....

/usr/bin/install -d ./htdocs/static/js
cd . && /Users/allenharper/git/djaoapp/installTop/bin/python3 manage.py generate_i18n_js htdocs/static/js/djaoapp-i18n.js
Use Jinja2 templates engine.
Traceback (most recent call last):
  File "/Users/allenharper/git/djaoapp/installTop/lib/python3.7/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/allenharper/git/djaoapp/installTop/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

Then, after many hours of troubleshooting, I arrive at this fatal issue:
(installTop) Allens-Mac:djaoapp allenharper$ python3 manage.py migrate --run-syncdb
...
...
django.db.utils.OperationalError: Problem installing fixtures: no such table: saas_organization__old

That appears to be linked to this issue: https://github.com/djaodjin/djaoapp/issues/72
After working down that rabbit hole, I found that the advice there to downgrade sqlite to 3.24.0 does not work...same error.

So, I am officially stuck.

**Comment by harperaa** [comment]
Fixed, used 'brew reinstall python3', then 'pip install virtualenv', that linked in python3 into the virtual environment correctly and got past the issues.  Then, had one more issue, when performing 'make initdb', had error that readline library was not found.
Did the following to resolve that...on osx 10.14.5:
brew install coreutils
echo 'alias readlink=greadlink' >> ~/.bash_aliases
ln -s /usr/local/opt/readline/lib/libreadline.8.dylib /usr/local/opt/readline/lib/libreadline.7.dylib

**Comment by smirolo** [comment]
Thank you Allen for the update on this issue.

We usually test Python2 on CentOS7 because Python2 is still an active version until Jan 2020. For most purposes, it is best to run djaoapp with Python3.

Here the commands used on OSX (10.12.6) to run under Python2 (with MacPorts).

    sudo port install py27-cryptography py27-pynacl py27-bcrypt py27-cairocffi
    virtualenv-2.7 --system-site-packages .virtualenv
    source .virtualenv/bin/activate
    pip install cairosvg==1.0.22 tinycss2==0.6.1 WeasyPrint==0.42.3
    pip install -r requirements.txt
    make install-conf
    make build-assets
    make initdb

**Comment by harperaa** [comment]
Thanks. Can you guys make any recommendations or share lessons learned with various hosting: aws, heroku, etc. any tips and comforts would be great. Also, a dockerfile would be great too. 

Allen Harper
