### ISSUE TITLE
coupons page: adds plan and nb_attempts to UI

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#117]
The `Coupon` model supports restricting usage to a specific provider plan as well as the number of times the coupon can be used. Both fields should should percolate into the UI.

**Comment by knivets** [comment]
How should the plan provider restriction look like in UI?

**Comment by smirolo** [comment]
![Screen Shot 2019-08-20 at 8 28 23 AM](https://user-images.githubusercontent.com/3732869/63361176-850d6f80-c324-11e9-9fbc-9fc26ccc7344.png)
A drop-down labelled "Restricted To:" with the active provider plans and an extra option "None", between "Expires:" and the coupon description.
