### ISSUE TITLE
layout of Funds page

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#118]
1/ The heading section takes too much space on mobile.
2/ The sort icons should always be aligned with the column header.
3/ Dates should be displayed on a single line.

![Screen Shot 2019-08-02 at 4 52 13 AM](https://user-images.githubusercontent.com/3732869/62369031-2ef69a80-b4e3-11e9-8a8e-39326fe13a5c.png)

Both the "Funds" and "Billing" tabs (`djaoapp/templates/saas/billing/transfers.html` and `djaoapp/templates/saas/billing/index.html`) use `djaoapp/templates/saas/_transactions.html` to display a table of `Transaction`.

Ideally the date and amount would display on a single line and the description on a following line on mobile. It is also possible to reduce the font-size as a stop gap measure.

**Comment by jpoechill** [comment]
I believe this issue should be considered resolved!

Attaching screenshots as evidence.

![screencapture-localhost-8000-billing-djaoapp-transfers-2019-10-30-14_34_49](https://user-images.githubusercontent.com/7801775/67900967-d3a86880-fb22-11e9-9a4c-067df99f8661.png)
![screencapture-localhost-8000-billing-djaoapp-transfers-2019-10-30-14_29_35](https://user-images.githubusercontent.com/7801775/67900969-d440ff00-fb22-11e9-9d4e-6d25b40ca0a1.png)

**Comment by smirolo** [comment]
Agreed.
