### ISSUE TITLE
connected profiles: alignment and text edit

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#150]
![Screen Shot 2019-09-03 at 5 53 45 AM](https://user-images.githubusercontent.com/3732869/64175241-c2d3c300-ce0f-11e9-8167-80d4bf9ab390.png)

**Comment by jpoechill** [comment]
updated in #157.

**Comment by knivets** [comment]
Is this fixed?

**Comment by jpoechill** [comment]
hey Dima, yes. :))
