### ISSUE TITLE
Admin dashboard: Profile Page shows empty

### ISSUE THREAD

**Issue by jpoechill** [djaodjin/djaoapp#155]
Current Behavior:
The original content will load briefly and be visible just for a few split seconds before clearing and showing empty.

Expected Behavior:
The page should load with content and form data.

Screenshot:
![Screen Shot 2019-09-13 at 1 52 43 PM](https://user-images.githubusercontent.com/7801775/64894269-1c1ccd00-d62e-11e9-9953-32662e0e5ac5.png)

**Comment by smirolo** [comment]
Upload profile picture is a feature still Work-in-Progress but the previous commit fixes this issue.
