### ISSUE TITLE
Date format in From/To input fields

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#21]
Here screenshot of AngularJS version
![date-format-angularjs](https://user-images.githubusercontent.com/3732869/49617984-ad5a6700-f96b-11e8-9856-a9ec2805b17b.png)

Here screenshot of Vue.js version
![date-format-vuejs](https://user-images.githubusercontent.com/3732869/49617992-b814fc00-f96b-11e8-8b48-98359f4f6e26.png)

**Comment by knivets** [comment]
Fixed in https://github.com/djaodjin/djaoapp/commit/a468a248d4126ad8dfce341637b43e9469c4cad5
