### ISSUE TITLE
Drag-n-drop on rules table

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#22]
Somehow I screwed up the drag-n-drop functionality on vue.js while trying to get both angularjs and vuejs into the templates but I cannot tell how. Looks like the code is the same as it was on the vuejs branch.

**Comment by knivets** [comment]
The plugin used was very fragile, so no wonder, though that was the quickest option.

**Comment by knivets** [comment]
OK, so the reason why it stopped working is that you moved the template out of the `<script>` tag, that's the problem with this plugin -- somehow it only works if the template is inside the `<script>` tag. What should I do here? Should we find another plugin?

**Comment by knivets** [comment]
OK, I replace the fragile plugin with another one, so it should work now.

**Comment by knivets** [comment]
Fixed in https://github.com/djaodjin/djaoapp/commit/0c91b5d9553bc19552e12ebda12d0d63251f0a10
