### ISSUE TITLE
date input in revenue page

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#23]
Another thing I seem to have messed up in the merge.
![date-format-vuejs](https://user-images.githubusercontent.com/3732869/49618754-894c5500-f96e-11e8-859b-30b23c70bc8a.png)

**Comment by knivets** [comment]
Fixed in https://github.com/djaodjin/djaoapp/commit/4f6f01270ebee736a9c245bf45e2493ffa89b8af
