### ISSUE TITLE
Roles page subscriber section is broken.

### ISSUE THREAD

**Issue by knivets** [djaodjin/djaoapp#25]
http://localhost:8000/profile/demo236/roles/manager/

**Comment by smirolo** [comment]
Yes. But it is an real organization profile or a personal profile (1-to-1 btw User and Organization)?

**Comment by knivets** [comment]
http://localhost:8020/profile/cowork/roles/manager/
<img width="1392" alt="screen shot 2018-12-11 at 12 05 24" src="https://user-images.githubusercontent.com/1903479/49779537-16135c00-fd3d-11e8-9ed9-0380f0dee89e.png">

**Comment by smirolo** [comment]
This issue has disappeared. most likely a difference in versions between the template and the djaodjin-saas-vuejs code used.
