### ISSUE TITLE
use Role.title consistently

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#26]
In the roles pages (manager/contributor) sometimes the `role_descr.slug` is used instead of `role_descr.title`. This is an artifact of the fact that `role_descr.title` is plural (ex: Managers) and used as such in the `_subscriber_sidebar.html` sidebar menus.

What should happen is:
1. Declare singular form in the fixtures (ex: Manager)
2. consistently use `role_descr.title` in the templates
3. Use a `|pluralize` template tag where necessary

Bonus: replace `Manager` by `Profile manager` as a title for the `manager` slug. `Manager` has a certain company hierarchical connotation that confuses some users. `Profile manager` clearly applies to the website/product.

**Comment by knivets** [comment]
2) slug is not used anywhere to display role title as far as I've looked
3) what about places where `title` is rendered by JS?

**Comment by smirolo** [comment]
Implemented in commit 1e98a548
