### ISSUE TITLE
Saving a text on app landing page produces CSRF missing error

### ISSUE THREAD

**Issue by knivets** [djaodjin/djaoapp#39]
http://localhost:8000/app/cowork/
<img width="1392" alt="screen shot 2019-02-06 at 11 56 30" src="https://user-images.githubusercontent.com/1903479/52321236-4a865a00-2a06-11e9-8556-c8c3de92617b.png">

**Comment by smirolo** [comment]
fixed in [djaodjin-pages commit 1036e47d](https://github.com/djaodjin/djaodjin-pages/commit/1036e47d42aa47a74d332665a0104fedbf541664).
