### ISSUE TITLE
display subscribers per plan

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#5]
Add an URL `/profile/djaoapp/plans/managed/subscribers/` which shows the list of all subscribers (churned and active) to a `Plan` as retrieved by the API end-point.

**Comment by knivets** [comment]
So I guess this should be added to djaodjin-saas first and then included in djaoapp?

**Comment by knivets** [comment]
OK, so there is a `/profile/djaoapp/plans/managed/subscribers/` view in djaodjin-saas already. It currently makes a request to `api/profile/cowork/plans/basic/subscriptions/` which only returns active subscribers I guess. BTW, I see terms subscribers and subscriptions are often used interchangeably, so maybe we should stick to one or is there any significance? I also checked djaoapp and there is a `profile/djaoapp/subscribers` page which shows "registered", "active", and "churned" subscribers, it makes requests to `metrics/cowork/churned`, etc -- I guess we can't use those?

**Comment by knivets** [comment]
OK, so after reading the code I think `api/profile/cowork/plans/basic/subscriptions/` returns all subscriptions. So if this is the correct thing, it is already in djaoapp http://localhost:8000/profile/djaoapp/plans/basic/subscribers/.

**Comment by smirolo** [comment]
The API and view end-points are already there (from [djaodjin-saas](https://github.com/djaodjin/djaodjin-saas). I see a vue.js templates created at commit 29d152c6. 

Guess just need to link to that page from the `/profile/{organization}/plans/{plan}/` page then and close the issue.

**Comment by smirolo** [comment]
done before PR #47
