### ISSUE TITLE
Can't make a registered user a profile manager

### ISSUE THREAD

**Issue by knivets** [djaodjin/djaoapp#75]
Typeahead treats username as email address of a person I want to invite.

**Comment by smirolo** [comment]
This issue will be fixed when upgrading to a new version of djaodjin-signup that includes [commit 70ad996d6](https://github.com/djaodjin/djaodjin-signup/commit/70ad996d6539ce9fa63ff69e2e34df395e0009ea).

**Comment by smirolo** [comment]
upgraded to djaodjin-signup 0.2.9 in [commit 5aad9e86](https://github.com/djaodjin/djaoapp/commit/5aad9e86877b7485fb52a84f67e9382e86358b3f#diff-b4ef698db8ca845e5845c4618278f29a)
