### ISSUE TITLE
Updates in accessibles page

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#78]
1. Show "accept grant" button when a Role has a `grant_key`.
2. Remove "From" and "To" date fields.
3. use Organization/profile cards (ref: #49 )
4. Add "Home" and "Settings" link in card to match the dropdown menu in menubar.
4. Remove "Create New" button and add a checkbox "I am a profile manager for this account" in the invite dialog modal when the profile could not be found.
![Screen Shot 2019-04-02 at 9 42 49 PM](https://user-images.githubusercontent.com/3732869/55453621-78fd5d00-5591-11e9-9d24-0a19a52d8de1.png)

**Comment by smirolo** [comment]
Login as brett (password: yoyo) and browse to http://localhost:8000/users/brett/roles/ for testing updates.

**Comment by knivets** [comment]
I'm not sure why should we use profile cards here -- each card will look almost identical and waste a lot of space.
<img width="524" alt="Screen Shot 2019-04-12 at 16 49 46" src="https://user-images.githubusercontent.com/1903479/56042147-09326380-5d43-11e9-9535-e42afd5c1740.png">

**Comment by smirolo** [comment]
We don't want a user card here. We want an Organization card. User accessibles is the list of organizations accessible by a user through a role. It is the dual of the organization roles page.
We want a card that looks a bit like the menubar dropdown.

![Screen Shot 2019-04-16 at 10 14 22 AM](https://user-images.githubusercontent.com/3732869/56230174-9bcb4f00-6030-11e9-9562-edb67a7be1ef.png)
