### ISSUE TITLE
Add i18n wrappers in Jinja2 templates

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#84]

**Comment by knivets** [comment]
But they are already added by including jinja2 [i18n extension](http://jinja.pocoo.org/docs/2.10/templates/#i18n). Am I missing something?

**Comment by smirolo** [comment]
The templates need to be edited to add `{% trans %}` statements.
```
- Subscribers
+{% trans %}Subscribers{% endtrans %}
```
