### ISSUE TITLE
use infinite scroll for pagination on mobile

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaoapp#91]
keep the click through page number on desktop

**Comment by smirolo** [comment]
1/ On Funds page, infinite scroll is working as expected loading another page once reaching the end of page. It is though difficult to read what was there and what was just loaded. It takes a while to see where I was and not miss a record entry. It would be beneficial to highlight the first row of the newly loaded page (with a different background color for example).
2/ The implementation at commit 44378c02 does not keep the "page number" footer on desktop for the Funds page as was expected per the issue description.
3/ The Coupons page does not implement infinite-scroll.

**Comment by knivets** [comment]
1) I have no idea how to test Funds page since I have the Stripe error.
2) Did you mean to keep the old-style manual pagination for desktop and use infinitescroll on mobile?

**Comment by smirolo** [comment]
1. Because `templates/saas/billing/index.html` (subscriber billing history) and `templates/saas/billing/transfers.html` (provider payouts) both include `saas/_transactions.html`, testing the subscriber billing history page should be enough.
2. Correct.

**Comment by smirolo** [comment]
Completed at commit 68375a1e.
